--- #YAML:1.0
name:               Catalyst-Controller-LeakTracker
version:            0.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::LeakTracker:  0
    Catalyst::Runtime:    5.8
    Data::Dumper:         0
    Devel::Cycle:         0
    Devel::Size:          0
    Number::Bytes::Human:  0.07
    Template::Declare:    0.42
    Test::More:           0.88
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
